services:
  sewlesew_db:
    image: postgres:16-alpine
    container_name: sewlesew-db
    restart: always
    environment:
      POSTGRES_USER: precious
      POSTGRES_PASSWORD: sewLesew3_db
      POSTGRES_DB: sewlesew_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
