services:
  - type: web
    name: sew-lesew-backend
    runtime: node
    repo: https://github.com/precious161/Sew-Le-Sew-A-unified-Donation-Platform
    branch: main
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://sew-lesew-frontend.onrender.com
      - key: API_URL
        sync: false
